In [79]:
import numpy as np  
import pandas as pd  

In [228]:
#importing Dataset
dataset = pd.read_excel(r'F:\Project\Machine Learning & Artificial Intelligence\Project 1-Major Depressive Disorder\Dataset\delta_pow.xlsx')
dataset.head()

ch1       ch2       ch3       ch4       ch5       ch6       ch7  \
0  0.000859  0.007251  0.031355  0.969053  0.030961  0.969093  0.923795   
1  0.000004  0.019063  0.112936  0.890142  0.109903  0.890142  0.920085   
2  0.000012  0.042204  0.196819  0.806375  0.193586  0.806375  0.920142   
3  0.000051  0.009729  0.050948  0.950224  0.049838  0.950226  0.920380   
4  0.119989  1.000000  0.139289  0.635711  0.358702  0.641380  1.000000   

        ch8       ch9      ch10      ch11      ch12      ch13      ch14  \
0  0.997378  0.993423  0.033978  0.002136  0.004511  0.009684  0.989910   
1  0.999242  0.945558  0.119978  0.000006  0.021626  0.122571  0.881118   
2  0.996710  0.880374  0.210215  0.000013  0.039009  0.178987  0.824861   
3  0.997855  0.984149  0.054583  0.000474  0.014549  0.047543  0.952641   
4  0.000000  0.768229  0.390370  0.309826  1.000000  0.067497  0.734294   

       ch15      ch16      ch17      ch18      ch19  classifier  
0  0.009908  0.989967  0.721588  0.996737  0.996322           0  
1  0.118815  0.881117  0.705132  0.999314  0.926128           0  
2  0.174958  0.824861  0.705226  0.998066  0.881943           1  
3  0.047267  0.952653  0.709674  0.998886  0.976715           0  
4  0.257425  0.742593  0.986523  0.000000  0.843195           0

In [229]:
#seeing the charts
X=dataset.iloc[:,0:19]
X.head()

ch1       ch2       ch3       ch4       ch5       ch6       ch7  \
0  0.000859  0.007251  0.031355  0.969053  0.030961  0.969093  0.923795   
1  0.000004  0.019063  0.112936  0.890142  0.109903  0.890142  0.920085   
2  0.000012  0.042204  0.196819  0.806375  0.193586  0.806375  0.920142   
3  0.000051  0.009729  0.050948  0.950224  0.049838  0.950226  0.920380   
4  0.119989  1.000000  0.139289  0.635711  0.358702  0.641380  1.000000   

        ch8       ch9      ch10      ch11      ch12      ch13      ch14  \
0  0.997378  0.993423  0.033978  0.002136  0.004511  0.009684  0.989910   
1  0.999242  0.945558  0.119978  0.000006  0.021626  0.122571  0.881118   
2  0.996710  0.880374  0.210215  0.000013  0.039009  0.178987  0.824861   
3  0.997855  0.984149  0.054583  0.000474  0.014549  0.047543  0.952641   
4  0.000000  0.768229  0.390370  0.309826  1.000000  0.067497  0.734294   

       ch15      ch16      ch17      ch18      ch19  
0  0.009908  0.989967  0.721588  0.996737  0.996322  
1  0.118815  0.881117  0.705132  0.999314  0.926128  
2  0.174958  0.824861  0.705226  0.998066  0.881943  
3  0.047267  0.952653  0.709674  0.998886  0.976715  
4  0.257425  0.742593  0.986523  0.000000  0.843195

In [230]:
y=dataset.iloc[:,19]
y.head()

0    0
1    0
2    1
3    0
4    0
Name: classifier, dtype: int64

In [231]:
#splitting Dataset into train & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0) 

In [232]:
#applying KNN classifier
from sklearn.neighbors import KNeighborsClassifier

In [233]:
classifier=KNeighborsClassifier(n_neighbors=9)
classifier

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [234]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0], dtype=int64)

In [235]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[6, 1],
       [3, 2]], dtype=int64)

In [236]:
a=cm[0][0]
b=cm[0][1]
c=cm[1][0]
d=cm[1][1]
#calculation Error,Accuracy,Sensitivity and Prediction
Err=(b+c)/(a+b+c+d)
Acc=(a+d)/(a+b+c+d)
SN=a/(a+c)
Prec=a/(a+b)
print(cm)
print('Accuracy=',Acc*100,'%')
print('Error=',Err*100,'%')
print('Sensitivity=',SN*100,'%')
print('Prediction=',Prec*100,'%')

[[6 1]
 [3 2]]
Accuracy= 66.66666666666666 %
Error= 33.33333333333333 %
Sensitivity= 66.66666666666666 %
Prediction= 85.71428571428571 %
