In [79]:
import numpy as np  
import pandas as pd  

In [210]:
#importing Dataset
dataset = pd.read_excel(r'F:\Project\Machine Learning & Artificial Intelligence\Project 1-Major Depressive Disorder\Dataset\alpha power.xlsx')
dataset.head()

ch1       ch2       ch3       ch4       ch5       ch6       ch7  \
0  1.000000  0.000161  0.000002  0.003590  0.002766  0.996329  0.003471   
1  0.900743  0.155649  0.000003  0.025983  0.153739  0.851107  0.148887   
2  0.821576  0.249583  0.000003  0.023302  0.226832  0.784104  0.215857   
3  0.973961  0.051798  0.001622  0.024406  0.107861  0.893625  0.106025   
4  0.852021  0.266569  0.028317  0.516520  0.068056  0.803914  0.194078   

        ch8       ch9      ch10      ch11      ch12      ch13      ch14  \
0  0.996328  0.929128  0.991803  0.999075  0.003813  0.000272  0.006008   
1  0.851078  0.929139  0.998793  0.900432  0.153924  0.000011  0.024846   
2  0.784060  0.929139  0.998472  0.840509  0.222680  0.000029  0.055637   
3  0.893754  0.935717  1.000000  0.935111  0.110128  0.000212  0.018927   
4  0.806501  0.981416  0.628486  0.903257  0.202386  0.077599  0.695049   

       ch15      ch16      ch17      ch18      ch19  Result  
0  0.018586  0.980844  0.019072  0.980852  0.529853       0  
1  0.164728  0.838194  0.161759  0.838194  0.525993       0  
2  0.297828  0.704763  0.295206  0.704763  0.526313       1  
3  0.073097  0.926146  0.073805  0.926151  0.529040       0  
4  0.135323  0.692614  0.305813  0.694762  0.864017       0

In [211]:
#seeing the charts
X=dataset.iloc[:,0:19]
X.head()

ch1       ch2       ch3       ch4       ch5       ch6       ch7  \
0  1.000000  0.000161  0.000002  0.003590  0.002766  0.996329  0.003471   
1  0.900743  0.155649  0.000003  0.025983  0.153739  0.851107  0.148887   
2  0.821576  0.249583  0.000003  0.023302  0.226832  0.784104  0.215857   
3  0.973961  0.051798  0.001622  0.024406  0.107861  0.893625  0.106025   
4  0.852021  0.266569  0.028317  0.516520  0.068056  0.803914  0.194078   

        ch8       ch9      ch10      ch11      ch12      ch13      ch14  \
0  0.996328  0.929128  0.991803  0.999075  0.003813  0.000272  0.006008   
1  0.851078  0.929139  0.998793  0.900432  0.153924  0.000011  0.024846   
2  0.784060  0.929139  0.998472  0.840509  0.222680  0.000029  0.055637   
3  0.893754  0.935717  1.000000  0.935111  0.110128  0.000212  0.018927   
4  0.806501  0.981416  0.628486  0.903257  0.202386  0.077599  0.695049   

       ch15      ch16      ch17      ch18      ch19  
0  0.018586  0.980844  0.019072  0.980852  0.529853  
1  0.164728  0.838194  0.161759  0.838194  0.525993  
2  0.297828  0.704763  0.295206  0.704763  0.526313  
3  0.073097  0.926146  0.073805  0.926151  0.529040  
4  0.135323  0.692614  0.305813  0.694762  0.864017

In [212]:
y=dataset.iloc[:,19]
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Result, dtype: int64

In [213]:
#splitting Dataset into train & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0) 

In [214]:
#applying KNN classifier
from sklearn.neighbors import KNeighborsClassifier

In [215]:
classifier=KNeighborsClassifier(n_neighbors=9)
classifier

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [216]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1], dtype=int64)

In [217]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[5, 2],
       [0, 5]], dtype=int64)

In [218]:
a=cm[0][0]
b=cm[0][1]
c=cm[1][0]
d=cm[1][1]
#calculation Error,Accuracy,Sensitivity and Prediction
Err=(b+c)/(a+b+c+d)
Acc=(a+d)/(a+b+c+d)
SN=a/(a+c)
Prec=a/(a+b)
print(cm)
print('Accuracy=',Acc*100,'%')
print('Error=',Err*100,'%')
print('Sensitivity=',SN*100,'%')
print('Prediction=',Prec*100,'%')

[[5 2]
 [0 5]]
Accuracy= 83.33333333333334 %
Error= 16.666666666666664 %
Sensitivity= 100.0 %
Prediction= 71.42857142857143 %
